version: '3'
services:
  app-mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=app
    volumes:
      - ./dbbackup/init.sql:/docker-entrypoint-initdb.d/init.sql
  app-backend:
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=app-mysql
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=secret
      - DATABASE_NAME=app
      - GIN_MODE=release
    restart: on-failure
    depends_on:
      - app-mysql
