// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"app/application/use_case/user/create_user"
	"app/repository"
	"gorm.io/gorm"
)

// Injectors from injection.go:

func CreateUserHandler(db *gorm.DB) create_user.CreateUserHandler {
	userRepository := repository.NewUserRepository(db)
	createUserService := create_user.NewCreateUserService(userRepository)
	createUserHandler := create_user.NewCreateUserHandler(createUserService)
	return createUserHandler
}
